# Numpy array Basics

In [1]:
import numpy as np

In [2]:
l = list(range(1,11))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
my_array = np.array(l)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
2*my_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
for i in l:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
2**my_array

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

In [10]:
a = np.arange(1,13)

In [14]:
a = a.reshape(2,3,2)

In [15]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [13]:
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [16]:
a.shape

(2, 3, 2)

In [17]:
a.size

12

In [18]:
a.length

AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [19]:
len(a)

2

In [22]:
m = np.arange(1,101).reshape(25,4)

In [23]:
m[2,3]

12

In [24]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [26]:
a.tolist()

[[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]

In [27]:
m.tolist()

[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20],
 [21, 22, 23, 24],
 [25, 26, 27, 28],
 [29, 30, 31, 32],
 [33, 34, 35, 36],
 [37, 38, 39, 40],
 [41, 42, 43, 44],
 [45, 46, 47, 48],
 [49, 50, 51, 52],
 [53, 54, 55, 56],
 [57, 58, 59, 60],
 [61, 62, 63, 64],
 [65, 66, 67, 68],
 [69, 70, 71, 72],
 [73, 74, 75, 76],
 [77, 78, 79, 80],
 [81, 82, 83, 84],
 [85, 86, 87, 88],
 [89, 90, 91, 92],
 [93, 94, 95, 96],
 [97, 98, 99, 100]]

In [29]:
type(m.tolist())

list

In [36]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [40]:
m.flatten().tolist()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [41]:
m.size

100

In [42]:
m.T

array([[  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
         53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97],
       [  2,   6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,
         54,  58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98],
       [  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
         55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100]])

In [43]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [46]:
len(m.flatten())

100

In [48]:
m[1]

array([5, 6, 7, 8])

In [49]:
m[1,1]

6

In [51]:
m.flatten()[99]

100

In [ ]:
0.
